name: Release stage 2 - auto publish

on:
  pull_request:  # types AND paths
    types: [closed]
    paths: ['metomi/isodatetime/__init__.py']

env:
  # Best not to include the GH token here, only do it for the steps that need it
  MERGE_SHA: ${{ github.event.pull_request.merge_commit_sha }}

jobs:
  publish:
    if: >-  # NOTE: Can't use top-level env here unfortunately
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: ${{ env.MERGE_SHA }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        # return to 3.x once compatible with 3.10+ (pyuv)
        python-version: '3.9'

    - name: Get the version number
      uses: cylc/release-actions/stage-2/get-version-from-pr@v1

    - name: Bump dev version
      uses: MetRonnie/release-actions/stage-2/bump-dev-version@bump-dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        init-file: 'metomi/isodatetime/__init__.py'
