name: Release pt 1 - create release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number of the form 1.2.3'
        required: true
      branch:
        description: 'The branch to open the PR against'
        required: false
        default: 'master'

env:
  # Best not to include the GH token here, only do it for the steps that need it
  REPOSITORY: ${{ github.repository }}
  INIT_FILE: 'metomi/isodatetime/__init__.py'
  CHANGELOG_FILE: CHANGES.md
  PR_BRANCH_PREFIX: 'prepare-'
  VERSION: ${{ inputs.version }}
  BASE_REF: ${{ inputs.branch }}

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BASE_REF }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create & checkout PR branch
      uses: MetRonnie/release-actions/stage-1/checkout-pr-branch@gh-cli

    - name: Set the package version
      uses: MetRonnie/release-actions/stage-1/set-python-package-version@gh-cli
      with:
        init-file: ${{ env.INIT_FILE }}
        pypi-package-name: metomi-isodatetime

    - name: Update "released on" date in changelog
      continue-on-error: true
      uses: MetRonnie/release-actions/stage-1/update-changelog-release-date@gh-cli
      with:
        changelog-file: 'CHANGES.md'

    - name: Create pull request
      uses: MetRonnie/release-actions/stage-1/create-release-pr@gh-cli
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
