name: Create PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4

    - name: Create PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create \
          --title "Test PR" \
          --body "Hello, John" \
          --base master \
          --head prepare-34.5.7 \
          --draft \
          --assignee MetRonnie \
          --reviewer MetRonnie
