name: Release pt 1 - create release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number of the form 1.2.3'
        required: true
      branch:
        description: 'The branch to open the PR against'
        required: false
        default: 'master'

env:
  # Best not to include the GH token here, only do it for the steps that need it
  REPOSITORY: ${{ github.repository }}
  INIT_FILE: 'metomi/isodatetime/__init__.py'
  CHANGELOG_FILE: CHANGES.md
  PR_BRANCH_PREFIX: 'prepare-'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: MetRonnie/release-actions/stage-1/checkout-pr-branch@refactor
        with:
          python-version: '3.10'
