name: Release pt 1 - create release PR

on:
  workflow_dispatch:

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: 1.3.x
        fetch-depth: 0
        repository: cylc/cylc-uiserver

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Test build
      uses: cylc/release-actions/build-python-package@v1

    - name: Generate changelog
      run: |
        python3 -m pip install -e .[tests]
        towncrier build --yes
