name: Deploy

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - run: sudo apt-get update

    - name: Setup mail
      run: sudo apt-get install mailutils

    - name: Test mail
      env:
        RECIPIENT: ${{ secrets.EMAIL_ADDRESS }}
      run: |
        mail -s 'GH Actions test mail' "$RECIPIENT" <<< "${{ runner.os }},\n${{ github.action }},\n${{ github.sha }}"
        sleep 30
        mail
