name: Deploy

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Install apm (with Atom)
      env:
        DEB_FILE: atom-amd64.deb
      run: |
        wget -nv -O "$DEB_FILE" https://atom.io/download/deb &&
        sudo apt -qq install "./$DEB_FILE"
        rm "$DEB_FILE"
        apm --version

    - name: Checkout repo
      uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1

    - name: List files in repo
      run: |
        ls -a

    - name: Check release version matches package.json
      env:
        GH_REF: ${{ github.ref }}
      shell: node {0}
      run: |
        const matches = process.env.GH_REF.match(/refs\/tags\/v(.+)/);
        if (matches) {
          const releaseVer = matches[1];
          const packageVer = JSON.parse(fs.readFileSync('package.json')).version;
          if (releaseVer === packageVer) {
            console.log('Version: ${releaseVer}');
          } else {
            throw new Error(`Release version (${releaseVer}) does not match package.json version (${packageVer})`);
          }
        } else {
          throw new Error(`No tag detected in ref '${ref}'`);
        }
