name: Deploy

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2.3.1

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - run: |
        REF=${{ github.ref }}
        TAG=${REF/'refs/tags/'/}

        git checkout -b "release"
        echo "Ah ah ah! You didnt say the magic word" >> copy.md
        git add -A
        git commit -m "CI release" -m "Workflow: ${{ github.workflow }}" -m "Run number: ${{ github.run_number }}"

        # Print tags info:
        git for-each-ref refs/tags

        git push -f origin release
        # Set origin tag to this commit:
        git push -f origin HEAD:${{ github.ref }}

