name: Deploy

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Check release version matches package.json
      run: |
        # VERSION_TAG=$(node ./.github/bin/get-version-tag ${{ github.ref }})

        package_ver=$( node -pe 'JSON.parse(fs.readFileSync("package.json")).version' )
        release_ver=$( node -pe 'process.argv[1].match(/refs\/tags\/v(.+)/)[1]' ${{ github.ref }} )

        if [[ package_ver -eq release_ver ]]; then
          VERSION_TAG="v${release_ver}"
        else
          exit 1
        fi
    
    - run: echo "$VERSION_TAG"
        

        
