name: Deploy

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.1.0
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '12.x'
    
