name: Deploy

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2.3.1

    - run: |
        REF=${{ github.ref }}
        TAG=${REF/'refs/tags/'/}

        # git checkout -b "test"
        cp README.md copy.md
        git commit -a -m "CI release" -m "Commited by GitHub Actions. Workflow: ${{ github.workflow }}. Run number: ${{ github.run_number }}."

        # Print tags info:
        git for-each-ref refs/tags

        # Set origin tag to this commit:
        git push -f origin HEAD:${{ github.ref }}

