name: Deploy

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5


    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.1

    - name: Check release version matches package.json
      run: |
        export VERSION_TAG=$( node ./.github/bin/get-version-tag 'refs/tags/v0.0.1' )
        echo "$VERSION_TAG"
    
    - run: echo "$VERSION_TAG"
        

        
