name: Publish release

on:
  pull_request:  # types AND paths
    types: [closed]
    paths: ['hammond.txt']
    # Don't use branches as we might create release on any branch

env:
  # Best not to include the GH token here, only do it for the steps that need it
  REPOSITORY: ${{ github.repository }}

jobs:
  create-release-pr:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'prepare-')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Get the version number
      run: |
        VERSION=$( grep -oP "(?<=prepare-).*" <<< '${{ github.head_ref }}' )
        if [[ -z "$VERSION"]]; then
          echo "::error :: Could not get version name from PR branch name '${HEAD_REF}'"
          exit 1
        fi
        echo "::set-env name=VERSION::$VERSION"

    # - name: Checkout repo
    #   uses: actions/checkout@v2.3.1

    # - name: Configure git
    #   run: |
    #     git config --global user.name "github-actions[bot]"
    #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    #     BRANCH_NAME="prepare-${VERSION}"
    #     git checkout -b "$BRANCH_NAME"

    #     echo "::set-env name=BRANCH_NAME::$BRANCH_NAME"

    # - name: Commit & push
    #   id: push
    #   run: |
    #     echo "Find Nedry! Check the vending machines!" > hammond.txt
    #     git add hammond.txt
    #     git commit -m "Create hammond.txt"
    #     git push origin "$BRANCH_NAME"

    - name: Create the release
      uses: actions/create-release@v1.1.2
      with:
        commitish: ${{ github.event.pull_request.merge_commit_sha }}
        tag_name: ${{ env.VERSION }}
        release_name: isodatetime ${{ env.VERSION }}
        body: TODO # TODO: get release number; add description field in the create-release-pr workflow input? Possibly preview this info in the PR?
        draft: true



    - name: Checkout repo
      uses: actions/checkout@v2.3.1

    - run: |
        pwd
        cd $( mktemp -d )
        pwd
        echo '${{ github.workspace }}'

    - run: pwd
